### ISSUE TITLE
default_so_paths in libopencl-stub are wrong for 64 bit

### ISSUE THREAD

**Issue by grindaah** [bbodin/slambench-android#2]
+static const char *default_so_paths[] = {    // Android - 64bit first

```
+                                           "/vendor/lib64/egl/**libGLES_mali.so**",
+                                           "/system/lib64/libOpenCL.so",
+                                           // Android                                                                    
                                             "/system/vendor/lib/egl/libGLES_mali.so",
+                                            "/system/vendor/lib/libOpenCL.so",
+                                            "/system/lib/libOpenCL.so",
                                             "/system/vendor/lib/libPVROCL.so",
                                             "/data/data/org.pocl.libs/files/lib/libpocl.so",
```

I assume for now, that this code patch is applying during build process after libopencl-stub downloaded from somewhere.
Note the bold libGLES - this causes unavailability to find OpenCL lib and following crash.
Also, i am not sure about other stuff here

**Comment by bbodin** [comment]
So you had to remove the line /vendor/lib64/egl/libGLES_mali.so to get it work ?

**Comment by grindaah** [comment]
Not exactly.
The problem is that list doesn't contain proper path for some of the ARM64 phones, which is:
/vendor/lib64/libOpenCL.so
I am not sure about this driver lib, initially i was thinking, that this shouldn't be in the list. I will google about that.
Anyway, can you tell me, what kind of patch will you prefer?
You are holding *.patch files inside your repo and if I'll "patch" your patch - it will contain your patch for libopencl-stub as well.
I think, good variant is create another patch and add "git apply" for it into Makefile: dependencies just after yours.
This will fix the thing

**Comment by bbodin** [comment]
I see your point. My problem is that each constructor use a different path for their OpenCL driver.   Some of these file name are shared by constructors but they do not necessarily share the same functions. I had to patch opencl-stub to get OpenCL working on some particular phones.
Anyway, I rather keep one patch file only for this particular file change, I will do it today. 
I will add /vendor/lib64/libOpenCL.so in the list at the first place, and later I will think about a safer solution for opencl-stub in general (or maybe it has been update since ...I will have a look).

**Comment by bbodin** [comment]
I updated accordingly a few weeks ago, I close the issue.
